# Generated by Django 3.2.4 on 2021-06-25 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('port_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_protocol', models.CharField(choices=[('tcp', 'tcp'), ('udp', 'udp')], default='tcp', max_length=3)),
                ('source_ip', models.CharField(max_length=60)),
                ('expiry_period', models.DurationField(default=datetime.timedelta(seconds=14400))),
                ('forwarder_port', models.CharField(max_length=10)),
                ('destination_ip', models.CharField(max_length=60)),
                ('destination_port', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=False)),
                ('renewal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
