# Generated by Django 3.2.4 on 2021-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='expiry_task_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
